Add machine parsable info.json files
srcclr/efda pull request #2
Opened 2018-07-14 05:06 UTC by Ayrx

This PR adds an `info.json` file to each EFDA sub-project containing the number of vulnerabilities, direct dependencies and transitive dependencies.

2018-07-18 05:28 UTC, hendychua requested changes
Looks good overall but there are a couple of changes required. Also, I'd suggest verifying the vulnerabilities data manually (especially the premium ones), as part of the other project requirement.

2018-07-18 05:28 UTC, hendychua commented on golang/glide/only-glide.yaml/info.json
> +    "vulnerabilities": 2,
According to srcclr scan output, there are 3 vulnerabilities:
```
Vulnerabilities - Public Data
CVE-2016-9121                             High Risk       Invalid Curve Attack                                    github.com/square/go-jose 7f0dd80...
CVE-2016-9122                             Medium Risk     Signature Exploitation                                  github.com/square/go-jose 7f0dd80...

Vulnerabilities - Premium Data
NO-CVE                                    Medium Risk     Denial Of Service (DoS) Through An Integer Overflow     github.com/square/go-jose 7f0dd80...
```
Is this a typo or did you mean to count only public data? I think you should also include premium data if they are correct. You should verify it manually (check the registry page then follow the description and source code to verify the vulnerability).

2018-07-18 05:28 UTC, hendychua commented on java/jars/fat-jars/info.json
> +    "vulnerabilities": 3,
This is the project where owasp detected 1 more CVE than SourceClear. SourceClear has updated their database and it now shows 4 vulnerabilities. This has to be updated along with the [README](https://github.com/srcclr/efda/blob/master/java/jars/fat-jars/README.md). As with all other data, you should verify them manually first.

2018-07-18 05:49 UTC, Ayrx commented on golang/glide/only-glide.yaml/info.json
> +    "vulnerabilities": 2,
Ah sorry! This one is a typo, will fix it as soon so I can.

The data here is all from the numbers in the README.md of each EFDA project which I believe is accurate at the point in time you guys added it? It isn't from the available data of the SourceClear scanner.

2018-08-01 02:46 UTC, hendychua approved these changes

2018-08-01 02:53 UTC, hendychua approved these changes

2018-08-01 02:57 UTC, merged