Add Nuget projects.
srcclr/efda pull request #3
Opened 2018-07-15 09:49 UTC by Ayrx

This PR adds two EFDA projects for Nuget-based .NET projects.

1. In `efda/csharp/nuget/with-packages.config`, we have the dependencies specified in the `packages.config` file.
2. In `efda/csharp/nuget/with-packagereference`, we have the dependencies specified as `PackageReference` directives in the `.csproj`. file.

The diff is a bit messy right now as it includes the changes in #2. I'll rebase this PR once that has been merged so it's a little bit easier to review.

2018-07-18 05:57 UTC, hendychua requested changes
Looks good apart from a couple of typos. Good job finding the vulnerable method. Be prepared to explain the thought and research process of finding the vulnerable method (You must be certain that it is a vulnerable method).

2018-07-18 05:57 UTC, hendychua commented on csharp/nuget/with-packagereference/info.json
> +    "direct_dependencies"; 4,
There's a typo here: `;` -> `:`.

2018-07-18 05:57 UTC, hendychua commented on csharp/nuget/with-packages.config/info.json
> +    "direct_dependencies"; 4,
There's a typo here: `;` -> `:`.

2018-08-01 03:02 UTC, Ayrx commented
Rebased and ready for review.

2018-08-01 03:04 UTC, hendychua approved these changes

2018-08-01 03:04 UTC, merged